image: docker:latest
services:
    - docker:dind
stages:
    - Build image and Push to Docker Hub
docker build and push:
    stage: Build image and Push to Docker Hub
    only:
        - main
    before_script:
        - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    script:
        - docker info
        - docker build -t siddharth67/pp123:1.2.3 .
        - docker push siddharth67/pp123:1.2.3
