apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fuxcdbot
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: source-php-app
  update:
    path: ./k8s-manifests
    strategy: Setters
