apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: image-repo
  policy:
    semver:
      range: 9.x.0
