apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomize-php-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./k8s-manifests
  prune: false
  sourceRef:
    kind: GitRepository
    name: source-php-app
