apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: source-php-app
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  url: https://gitlab.com/sidd-harth/php-app
